(function () {
    'use strict';

    Peerio.UI.Settings2FA = React.createClass({
        mixins:[ReactRouter.Navigation],

        componentDidMount: function () {
        },

        removeDialog: function() {
            // this.replaceWith('/app/settings/account');
        },

        cancel: function () {
            // this.props.onCancel(this.props.address, this.refs.textInput.getDOMNode().value);
            this.removeDialog();
        },

        ok: function () {
            // this.props.onPrompt(this.props.address, this.refs.textInput.getDOMNode().value);
            this.removeDialog();
        },
        //--- RENDER
        render: function () {
            return (
                <div className="content-padded">
                    <div className="info-label">
                        Two factor authentication
                    </div>
                    <div class="text-input-label">
                        Use your favourite authentificator to enter the code below. Peerio recommends either Authy or FreeOTP.
                        <br/>
                        After that, please enter the six-digit code generated by authenticator to confirm setup.
                    </div>
                    <div>
                        <input 
                            className="txt-lrg text-center" 
                            ref="textInput" 
                            autoComplete="off" autoCorrect="off"
                            autoCapitalize="off" spellCheck="false"
                            value="EFAB101491901949" readonly="true"/>
                        <Peerio.UI.Tappable element="div" className="btn-lrg" 
                            onTap={this.ok}> 
                            Confirm 
                        </Peerio.UI.Tappable>
                    </div>
                </div>
            );
        }
    });

}());
